version: '3.1'

services:

  mysql:
    image: mysql
    container_name: mysql_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'students'
      MYSQL_ROOT_PASSWORD: 'root'

    ports:
      - '3306:3306'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080